theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  plausible: 
  persons:
    index:
      layout: grid
  posts:
    index:
      layout: grid
  breadcrumb:
    position: hero-start
  search:
    active: true
    position: footer
    appearance: both